//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWCF1
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class ProjectRoleDto
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int ProjectId { get; set; }
        [DataMember]
        public int UserId { get; set; }
        [DataMember]
        public string ProjectName { get; set; }
        [DataMember]
        public string UserName { get; set; }
        public ProjectRoleDto()
        {

        }
        public ProjectRoleDto(int projectId, int userId, string projectName, string userName)
        {
            this.ProjectId = projectId;
            this.UserId = userId;
            this.ProjectName = projectName;
            this.UserName = userName;
        }
    }
}
