//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWCF1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProjectDto> ProjectDtoes { get; set; }
        public virtual DbSet<SaveUserDto> SaveUserDtoes { get; set; }
        public virtual DbSet<UserDto> UserDtoes { get; set; }
        public virtual DbSet<ProjectRoleDto> ProjectRoleDtoes { get; set; }
    }
}
